# Dependabot configuration for GitHub Actions Template
# This file enables automatic dependency updates for npm packages and GitHub Actions

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "yourusername"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "@actions/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@actions/github"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "yourusername"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    ignore:
      # Ignore major version updates for critical actions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-node"
        update-types: ["version-update:semver-major"]
